
package com.view;

import com.models.storage.History;
import com.controllers.util.Response;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import com.controllers.*;
/**
 *
 * @author sebas
 */
public class CalculatorFrame extends javax.swing.JFrame {
    
    private History history;
    
    public CalculatorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Btnadd = new javax.swing.JButton();
        Btnsubtract = new javax.swing.JButton();
        Btnmultiply = new javax.swing.JButton();
        Btndivide = new javax.swing.JButton();
        Btnpotency = new javax.swing.JButton();
        Btnclearnum = new javax.swing.JButton();
        Btnupdateh = new javax.swing.JButton();
        Field1 = new javax.swing.JTextField();
        Field2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoryList = new javax.swing.JList<>();
        Field3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Calculator");

        Btnadd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btnadd.setText("Add");
        Btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnaddActionPerformed(evt);
            }
        });

        Btnsubtract.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btnsubtract.setText("Subtract");
        Btnsubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsubtractActionPerformed(evt);
            }
        });

        Btnmultiply.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btnmultiply.setText("Multiply");
        Btnmultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnmultiplyActionPerformed(evt);
            }
        });

        Btndivide.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btndivide.setText("Divide");
        Btndivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtndivideActionPerformed(evt);
            }
        });

        Btnpotency.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Btnpotency.setText("Potency");
        Btnpotency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnpotencyActionPerformed(evt);
            }
        });

        Btnclearnum.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Btnclearnum.setText("Clear numbers");
        Btnclearnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnclearnumActionPerformed(evt);
            }
        });

        Btnupdateh.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Btnupdateh.setText("Update history");
        Btnupdateh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnupdatehActionPerformed(evt);
            }
        });

        Field1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Field2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Number 1");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Number 2");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Result");

        HistoryList.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        HistoryList.setEnabled(false);
        jScrollPane1.setViewportView(HistoryList);

        Field3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Field3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Field3.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btnclearnum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Field1)
                            .addComponent(Field2)
                            .addComponent(Field3, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btnpotency, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btnmultiply, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(Btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btnsubtract, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(Btndivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btnupdateh, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btnupdateh))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Field2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Field3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btnadd)
                            .addComponent(Btnsubtract))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btndivide)
                            .addComponent(Btnmultiply))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btnpotency)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btnclearnum))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnaddActionPerformed
        // TODO add your handling code here
        String n1 = Field1.getText();
        String n2 = Field2.getText();
        Response res = AddControllers.createOperation(n1, n2);
        if (res.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, res.getMessage(), "Error " + res.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (res.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, res.getMessage(), "Error " + res.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else { 
            Field1.setText("");
            Field2.setText("");
            Field3.setText((String) res.getObject());
            
        }
        
    }//GEN-LAST:event_BtnaddActionPerformed

    private void BtnsubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsubtractActionPerformed
        // TODO add your handling code here:
         String n1 = Field1.getText();
        String n2 = Field2.getText();
        Response res = SubtractControllers.createOperation(n1, n2);
        if (res.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, res.getMessage(), "Error " + res.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (res.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, res.getMessage(), "Error " + res.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            Field1.setText("");
            Field2.setText("");
            Field3.setText((String) res.getObject());
        }
    }//GEN-LAST:event_BtnsubtractActionPerformed

    private void BtnmultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnmultiplyActionPerformed
        // TODO add your handling code here:
       String n1 = Field1.getText();
        String n2 = Field2.getText();
        Response res = MultiplyControllers.createOperation(n1, n2);
        if (res.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, res.getMessage(), "Error " + res.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (res.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, res.getMessage(), "Error " + res.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            Field1.setText("");
            Field2.setText("");
            Field3.setText((String) res.getObject());
        }
    }//GEN-LAST:event_BtnmultiplyActionPerformed

    private void BtndivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtndivideActionPerformed
        // TODO add your handling code here:
        String n1 = Field1.getText();
        String n2 = Field2.getText();
        Response res = DivideControllers.createOperation(n1, n2);
        if (res.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, res.getMessage(), "Error " + res.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (res.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, res.getMessage(), "Error " + res.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {    
            Field1.setText("");
            Field2.setText("");
            Field3.setText((String) res.getObject());
            
        }
    }//GEN-LAST:event_BtndivideActionPerformed

    private void BtnpotencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnpotencyActionPerformed
        // TODO add your handling code here
        String n1 = Field1.getText();
        String n2 = Field2.getText();
        Response res = PotencyControllers.createOperation(n1, n2);
        if (res.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, res.getMessage(), "Error " + res.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (res.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, res.getMessage(), "Error " + res.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            Field1.setText("");
            Field2.setText("");
            Field3.setText((String) res.getObject());
        }
    }//GEN-LAST:event_BtnpotencyActionPerformed

    private void BtnclearnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnclearnumActionPerformed
        // TODO add your handling code here:
        Field1.setText("");
        Field2.setText("");
        Field3.setText("");
    }//GEN-LAST:event_BtnclearnumActionPerformed

    private void BtnupdatehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnupdatehActionPerformed
        // TODO add your handling code here:
       Response history = HistoryControllers.getHistory();
        if (history.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, history.getMessage(), "An error has occurred !!! " + history.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (history.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, history.getMessage(), "An error has occurred !!!" + history.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            HistoryList.setModel((ListModel<String>) history.getObject()); 
        }  
    }//GEN-LAST:event_BtnupdatehActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnadd;
    private javax.swing.JButton Btnclearnum;
    private javax.swing.JButton Btndivide;
    private javax.swing.JButton Btnmultiply;
    private javax.swing.JButton Btnpotency;
    private javax.swing.JButton Btnsubtract;
    private javax.swing.JButton Btnupdateh;
    private javax.swing.JTextField Field1;
    private javax.swing.JTextField Field2;
    private javax.swing.JTextField Field3;
    private javax.swing.JList<String> HistoryList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
